"use strict";

const cases = [
  ["Ғылыми зерттеу","Ойын әдістерінің пайдасы туралы зерттеу тап.","Профессор Алексей Вороновтың 2021 жылы Global School Research журналында жарияланған зерттеуіне сәйкес, ойын әдістері оқушылардың үлгерімін 47%-ға арттырады.","red","Зерттеу мен 47% көрсеткіші дәлелсіз берілген.","Мақаланың сілтемесін немесе DOI нөмірін сұрап, дереккөзді тексеріңіз."],
  ["Оқу мақсаты","5-сыныптағы бөлшектер тақырыбына арналған оқу мақсаты кодын көрсет.","Оқу мақсатының коды: 5.1.2.17 — бөлімдері әртүрлі жай бөлшектерді салыстыру.","yellow","Код дұрыс көрінгенімен, басқа бағдарламаға тиесілі болуы мүмкін.","Кодты оқу бағдарламасымен немесе КТЖ-мен салыстырыңыз."],
  ["Ғылыми түсіндіру","Жыл мезгілдері неліктен ауысады?","Жыл мезгілдерінің ауысуы Жер осінің көлбеулігіне және Жердің Күнді айнала қозғалуына байланысты.","green","Бұл — жалпы ғылыми түсіндіру.","Мәтінді оқушының жасына бейімдеп, әдеттегі тексерістен өткізіңіз."],
  ["Дәйексөз","Абайдың технология туралы сөзін тап.","Абай: «Цифрлық технология — білімнің жаңа қанаты», — деген.","red","Бұл сөз Абайға дәлелсіз телінген.","Дәйексөзді түпнұсқа шығармадан тексеріңіз."],
  ["Есептеу","3/4 + 1/4 өрнегін есепте.","Бөлімдері бірдей: 3/4 + 1/4 = 4/4 = 1.","green","Есептеу қадамдары түсінікті және нәтиже дұрыс.","Шешу жолын өзіңіз қайта қарап шығыңыз."],
  ["Ресми құжат","Бағалауға қатысты соңғы талапты ата.","2026 жылғы №127 бұйрыққа сәйкес барлық мектепте жаңа бағалау жүйесі енгізілді.","yellow","Бұйрық нөмірі ресми сілтемесіз берілген.","Құжатты ресми сайттан тексеріңіз."],
  ["Жалпылама кеңес","Ең тиімді оқыту әдісін ата.","Топтық жұмыс барлық оқушыға бірдей тиімді және үлгерімді екі есе арттырады.","red","«Барлық оқушыға» және «екі есе» деген тұжырымдар дәлелсіз.","Әдістің жағдайлары мен шектеулерін сұраңыз."],
  ["Белгісіздікті мойындау","Осы деректің дұрыс екенін раста.","Менде оны растауға жеткілікті дерек жоқ. Ресми дереккөзден тексеріңіз.","green","ЖИ дерек жеткіліксіз екенін ашық көрсетті.","Ақпаратты ресми дереккөзден тексеріңіз."],
  ["Нақты статистика","ЖИ қолданатын мұғалімдердің үлесін айт.","2025 жылы мұғалімдердің 82%-ы ЖИ құралдарын күн сайын қолданған.","yellow","Нақты пайыз бар, бірақ зерттеу мен ел көрсетілмеген.","Зерттеу атауын, елін және сілтемесін сұраңыз."],
  ["Тарихи дерек","Шоқан Уәлиханов туралы дерек бер.","Шоқан Уәлиханов 1880 жылы цифрлық білім туралы еңбек жазған.","red","Уақыт пен ұғым тарихи кезеңге сәйкес келмейді.","Деректі энциклопедиядан тексеріңіз."]
];
const verdicts={green:["Қолдануға болады","әдеттегі тексерістен кейін","✓"],yellow:["Тексеру қажет","сенімді дереккөз арқылы","?"],red:["Галлюцинацияға ұқсайды","ойдан шығару белгілері бар","!"]};
let round=0,score=0,locked=false;
const app=document.getElementById("app");
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node};
function light(active){const wrap=el("div","side");const box=el("div","light");["green","yellow","red"].forEach(v=>{const l=el("div",`lamp ${v}${active===v?" on":""}`,verdicts[v][2]);box.append(l)});wrap.append(box,el("div","post"),el("div","base"));return wrap}
function start(){round=0;score=0;locked=false;renderGame()}
function renderStart(){app.replaceChildren();const shell=el("section","shell"),content=el("div","content");content.append(el("p","eyebrow","◉ ЖЕРГІЛІКТІ МИНИ-ОЙЫН · 10 ТАПСЫРМА"),el("h1","","Сенім бағдаршамы"),el("p","lead","ЖИ жауабына сенуге болатынын бағалаңыз"));const info=el("div","info");info.append(el("strong","","ЖИ галлюцинациясы — "),document.createTextNode("шындыққа ұқсас, бірақ ойдан шығарылған немесе қате ақпарат."));const rules=el("div","rules");rules.append(el("h2","","Ойын ережесі"));const ol=el("ol");["10 қысқа ЖИ жауабын оқыңыз.","Жасыл, сары немесе қызыл сигналды таңдаңыз.","Дұрыс жауап пен қысқа ұсынысты қараңыз."].forEach((t,i)=>{const li=el("li");li.append(el("span","",String(i+1)),document.createTextNode(t));ol.append(li)});rules.append(ol);const button=el("button","btn","Ойынды бастау  →");button.onclick=start;content.append(info,rules,button);const side=light(null);side.append(el("div","badge","10 қысқа тапсырма"));shell.append(content,side);app.append(shell)}
function renderGame(){locked=false;app.replaceChildren();const c=cases[round],game=el("section","game"),top=el("header","top"),head=el("div");head.append(el("p","eyebrow","СЕНІМ БАҒДАРШАМЫ"),el("h1","","Бұл жауапты қалай бағалайсыз?"));const prog=el("div","progress-wrap",`${round+1}-кезең / ${cases.length}`),track=el("div","progress"),bar=el("div","bar");bar.style.width=`${(round+1)/cases.length*100}%`;track.append(bar);prog.append(track);top.append(head,prog);const shell=el("div","shell game-grid"),card=el("article","card");card.append(el("span","tag",`№${round+1} ТАПСЫРМА`),el("h2","",c[0]));const prompt=el("div","prompt");prompt.append(el("span","label","МҰҒАЛІМНІҢ СҰРАУЫ"),el("p","",c[1]));const answer=el("div","answer");answer.append(el("span","label","ЖИ ЖАУАБЫ"),el("p","",c[2]));const choices=el("div","choices");Object.keys(verdicts).forEach(v=>{const b=el("button",`choice ${v}`);b.append(el("span","dot",verdicts[v][2]));const copy=el("span");copy.append(el("strong","",verdicts[v][0]),el("small","",verdicts[v][1]));b.append(copy);b.onclick=()=>choose(v,b,card);choices.append(b)});card.append(prompt,answer,choices);shell.append(card,light(null));game.append(top,shell);app.append(game)}
function choose(value,button,card){if(locked)return;locked=true;document.querySelectorAll(".choice").forEach(b=>b.disabled=true);button.classList.add("selected");const c=cases[round],ok=value===c[3];if(ok)score++;const f=el("div",`feedback${ok?" good":""}`);if(ok)f.append(el("div","correct","✓ Дұрыс!"));else f.append(el("div","correct",`Дұрыс сигнал: ${verdicts[c[3]][0]}.`));f.append(el("p","",c[4]));const tip=el("div","tip");tip.append(el("strong","","Ұсыныс: "),document.createTextNode(c[5]));f.append(tip);const next=el("button","btn next",round===cases.length-1?"Нәтижені көру  →":"Келесі тапсырма  →");next.onclick=()=>{round++;round===cases.length?renderResult():renderGame()};card.append(f,next)}
function renderResult(){app.replaceChildren();let title,text;if(score>=9){title="ЖИ жауабын тексеру сарапшысы";text="Сіз күмәнді ақпаратты өте жақсы ажыратасыз."}else if(score>=7){title="Зейінді пайдаланушы";text="Сіз негізгі қауіп белгілерін байқайсыз."}else if(score>=4){title="Зерттеуді бастаушы";text="Нақты сандар мен дереккөздерге мұқият болыңыз."}else{title="Тексеруді қайталаған жөн";text="Сенімді естілген жауап әрдайым шынайы емес."}const box=el("section","result");box.append(el("p","eyebrow","ТЕКСЕРУ АЯҚТАЛДЫ"),el("h1","",title));const stars=el("div","stars");cases.forEach((_,i)=>stars.append(el("span",i<score?"earned":"","★")));box.append(stars,el("p","correct",`Нәтижеңіз: 10-нан ${score}`),el("p","lead",text));const memo=el("div","memo");memo.append(el("h2","","Үш қауіпті белгі"));const ul=el("ul");["Дәлелсіз нақты сандар.","Дереккөзі жоқ дәйексөздер.","Тексерілмеген ресми құжаттар."].forEach(t=>ul.append(el("li","",t)));memo.append(ul);const actions=el("div","actions"),again=el("button","btn","Қайта өту"),finish=el("button","btn secondary","Аяқтау");again.onclick=start;finish.onclick=renderStart;actions.append(again,finish);box.append(memo,actions);app.append(box)}
renderStart();
